Script started on 2024-09-15 20:15:19-04:00
bash-4.4$ cd ~/os161/root/
bash-4.4$ cs161-gdb kernwl[K[Kel
[?1034hGNU gdb (GDB) 7.8
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-unknown-linux-gnu --target=mips-harvard-os161".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from kernel...done.
(gdb) target remote unit[Kx:.sockets/gdb
Remote debugging using unix:.sockets/gdb
__start () at /home/koleary6/os161/kern/arch/mips/mips/start.S:24
24	   addiu sp, sp, -20
(gdb) break menu
Breakpoint 1 at 0x80014818: file /home/koleary6/os161/kern/main/menu.c, line 646.
(gdb) c
Continuing.

Breakpoint 1, menu (args=0x8002a174 "") at /home/koleary6/os161/kern/main/menu.c:646
646		menu_execute(args, 1);
(gdb) where
#0  menu (args=0x8002a174 "") at /home/koleary6/os161/kern/main/menu.c:646
#1  0x800137ec in kmain (arguments=0x8002a174 "") at /home/koleary6/os161/kern/main/main.c:168
#2  0x800228b4 in __start () at /home/koleary6/os161/kern/arch/mips/mips/start.S:163
(gdb) detach
Detaching from program: /home/koleary6/os161/root/kernel, Remote target
Ending remote debugging.
(gdb) quit
bash-4.4$ exit
exit

Script done on 2024-09-15 20:16:23-04:00
