Script started on 2024-09-15 19:29:52-04:00
bash-4.4$ make
[36mGEN     (B[m/home/koleary6/os161/tags
[33mCLEAN   (B[m/home/koleary6/os161/kern/kernel
[36mGEN     (B[m/home/koleary6/os161/kern/compile/vers.c
*** This is ASST0 build #8 ***
[32mCC      (B[m/home/koleary6/os161/kern/compile/vers.c
[35mLINK    (B[m/home/koleary6/os161/kern/kernel
[34mINSTALL (B[m/home/koleary6/os161/root/kernel
bash-4.4$ cd~/o[K[K[K ~/oo[Ks161/root
bash-4.4$ sys161 kernel
sys161: System/161 release 2.0.8, compiled Jan 10 2022 16:03:24

OS/161 base system version 1.11gmu
Copyright (c) 2000, 2001, 2002, 2003
   President and Fellows of Harvard College.  All rights reserved.

Put-your-group-name-here's system version 0 (ASST0 #8)

Cpu is MIPS r2000/r3000
1872k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltimer0 at lamebus0
hardclock on ltimer0 (100 hz)
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lhd0 at lamebus0
lhd1 at lamebus0
lser0 at lamebus0
con0 at lser0
pseudorand0 (virtual)

Hello World
OS/161 kernel [? for menu]: p /sbin/poweroff
Operation took 0.000157120 seconds
OS/161 kernel [? for menu]: Shutting down.
The system is halted.
sys161: 106067251001 cycles (17703638343 run, 88363612658 global-idle)
sys161:   cpu0: 566874197 kern, 21 user, 0 idle; 0 ll, 0/0 sc, 0 sync
sys161: 354628 irqs 6 exns 0r/0w disk 17r/687w console 8r/0w/3m emufs 0r/0w net
sys161: Elapsed real time: 12.365739 seconds (8577.51 mhz)
sys161: Elapsed virtual time: 3557.230680412 seconds (25 mhz)
bash-4.4$ exit
exit

Script done on 2024-09-15 19:30:37-04:00
